spring.application.name=signature-app
spring.datasource.url=jdbc:postgresql://db.gdvqvdylznlnmcnmcyqb.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Signdbanas17
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
file.upload-dir=uploads
spring.security.user.name=disable
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohammedanas0617@gmail.com
spring.mail.password=vzpgnsflhjpglozz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
